name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: matanui159/mintboy-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Upload ROM
        uses: actions/upload-artifact@v1
        with:
          name: rom
          path: bin/rom.gb
